services:
  ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/model:/app/model
      - ./logs:/app/logs  # Volumen para logs persistentes
    environment:
      #- TF_FORCE_GPU_ALLOW_GROWTH=true
      #- LOG_LEVEL=INFO
      - CUDA_VISIBLE_DEVICES=-1  # Deshabilitar GPU
      - TF_CPP_MIN_LOG_LEVEL=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
        #reservations:
          #devices:
            #- driver: nvidia
             # count: 1
              #capabilities: [gpu]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: mental-health-network
    driver: bridge
