---
- name: Instalando paquete RPM
  hosts: 10.0.0.99
  become: yes
  vars:
    rpm_file: "mi_programa.rpm"
    dest_path: "/tmp/"

  tasks:
    - name: Copiando archivo RPM
      ansible.builtin.copy:
        src: "{{ rpm_file }}"
        dest: "{{ dest_path }}"
        mode: '0644'

    - name: Instalar paquete RPM
      ansible.builtin.command:
        cmd: "rpm -i {{ dest_path }}{{ rpm_file }}"
